name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tpayweb-v3-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run TPayWeb_V3 Playwright Tests
      run: npx playwright test Main/TPayWeb_V3/1_Login_TPayV3_Merchant.spec.ts

    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TPAYSECRETS }}
        publish_dir: ./allure-report
        publish_branch: gh-pages

    - name: Send email with test results for TPayWeb_V3
      if: always()
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: vasalanga@traxiontech.net
        subject: Playwright Test Result
        password: yszeszihrsqreloy
        to: salangavincent@gmail.com
        from: vasalanga@traxiontech.net 
        body: |
          The Playwright tests for TPayWeb_V3 have completed. Please find the Allure report at the following link: https://Dread-Vin.github.io/TraxionPay-V3/