name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-tpayweb-v3-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
        
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright Tests
      - name: Run TPayWeb_V3 Playwright Tests
        run: npx playwright test Main/TPayWeb_V3/1_Login_TPayV3_Merchant.spec.ts

      # Generate Allure Report
      - name: Generate Allure Report
        run: npm run allure:report
      
      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./allure-report
          
      # Upload Allure Report as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Send email with Allure report link
      - name: Send email with test results for TPayWeb_V3
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: vasalanga@traxiontech.net
          subject: Playwright Test Result
          password: yszeszihrsqreloy
          to: salangavincent@gmail.com
          from: vasalanga@traxiontech.net
          body: |
            The Playwright tests for TPayWeb_V3 have completed. Please find the Allure report at the following link:
            https://Dread-Vin.github.io/TraxionPay-V3/allure-report/index.html