name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  #schedule:
    #- cron: '0 */1 * * *' # Runs every 4 hours

jobs:
  run-tpayweb-v3-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run TPayWeb_V3 Playwright Tests
      run: npx playwright test Main/TPayWeb_V3/1_Login_TPayV3_Merchant.spec.ts
    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report
    - name: Serve Allure Report
      run: |
        npx allure open allure-report --port 8080 &
        echo "Allure report is being served at http://localhost:8080"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - name: Prepare email content
      id: prepare_email
      run: |
        DATE=$(date)
        TEST_RESULTS="<tr><td>Example Test Case</td><td>Passed</td><td>30s</td></tr>"
        EMAIL_CONTENT=$(cat html-report/email_template.html)
        EMAIL_CONTENT=${EMAIL_CONTENT//"{{DATE}}"/$DATE}
        EMAIL_CONTENT=${EMAIL_CONTENT//"{{TEST_RESULTS}}"/$TEST_RESULTS}
        EMAIL_CONTENT=${EMAIL_CONTENT//"{{CI_LINK}}"/"http://localhost:8080"}
        echo "$EMAIL_CONTENT" > html-report/email_content.html
    - name: Send email with test results for TPayWeb_V3
      if: always()
      uses: dawidd6/action-send-mail@v4
      with:
        connection_url: smtp://vasalanga@traxiontech.net:yszeszihrsqreloy@smtp.gmail.com:587
        subject: Playwright Test Results for TPayWeb_V3
        to: salangavincent@gmail.com
        from: vasalanga@traxiontech.net
        html_body: file://html-report/email_content.html