name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  #schedule:
    #- cron: '0 */1 * * *' # Runs every 4 hours

jobs:
  run-tpayweb-v3-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run TPayWeb_V3 Playwright Tests
      run: npx playwright test Main/TPayWeb_V3/1_Login_TPayV3_Merchant.spec.ts
    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report
    - name: Serve Allure Report
      run: |
        npx allure open allure-report --port 8080 &
        echo "Allure report is being served at http://localhost:8080"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    
    - name: Send email with test results for TPayWeb_V3
      if: always()
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: vasalanga@traxiontech.net
        subject: Playwright Test Result
        password: yszeszihrsqreloy
        to: salangavincent@gmail.com
        from: vasalanga@traxiontech.net 
        html_body: |
            <html>
            <head>
              <style>
                .email,
                .email * {
                  box-sizing: border-box;
                }
                .email {
                  height: 490px;
                  position: relative;
                }
                .bg {
                  background: #d9d9d9;
                  border-radius: 5px;
                  width: 590px;
                  height: 490px;
                  position: absolute;
                  left: 0px;
                  top: 0px;
                }
                .inner-bg {
                  width: 420px;
                  height: 359px;
                  position: static;
                }
                .rectangle-1 {
                  background: #ffffff;
                  border-radius: var(--corner-small, 8px) var(--corner-small, 8px) 0px 0px;
                  border-style: solid;
                  border-color: #706c6c;
                  border-width: 0.1px;
                  width: 420px;
                  height: 110px;
                  position: absolute;
                  left: 86px;
                  top: 65px;
                }
                .rectangle-2 {
                  background: #e7e4e4;
                  border-radius: 0px 0px 5px 5px;
                  border-style: solid;
                  border-color: #706c6c;
                  border-width: 0px 0px 0.1px 0px;
                  width: 420px;
                  height: 250px;
                  position: absolute;
                  left: 86px;
                  top: 174px;
                }
                .traxion-logo-1 {
                  width: 126px;
                  height: 48px;
                  position: absolute;
                  left: 232px;
                  top: 87px;
                  object-fit: cover;
                }
                .content {
                  background: #ffffff;
                  border-style: solid;
                  border-color: #000000;
                  border-width: 0.1px;
                  width: 310px;
                  height: 220px;
                  position: absolute;
                  left: 140px;
                  top: 148px;
                }
                .btn {
                  background: #2bbcff;
                  border-radius: 5px;
                  width: 84px;
                  height: 29px;
                  position: absolute;
                  left: 247px;
                  top: 299px;
                  overflow: hidden;
                }
                .btn a {
                  color: white;
                  text-decoration: none;
                  display: block;
                  height: 100%;
                  width: 100%;
                  text-align: center;
                  line-height: 29px;
                }
              </style>
            </head>
            <body>
              <div class="email">
                <div class="bg"></div>
                <div class="inner-bg">
                  <div class="rectangle-1"></div>
                  <div class="rectangle-2"></div>
                </div>
                <img class="traxion-logo-1" src="traxion-logo-10.png" />
                <div class="content">
                  <p>Dear User,</p>
                  <p>The Playwright tests for TPayWeb_V3 have been completed. You can view the detailed test results by clicking the button below.</p>
                </div>
                <div class="btn">
                  <a href="http://localhost:8080">View Report</a>
                </div>
              </div>
            </body>
            </html>