name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-tpayweb-v3-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run TPayWeb_V3 Playwright Tests
      run: npx playwright test Main/TPayWeb_V3/test.app.spec.ts

    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report 

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: allure-report
        keep_files: false

    - name: Get GitHub Pages URL
      id: get-url
      shell: pwsh  # Use PowerShell explicitly
      run: |
        # Extract the repository owner and name
        $repoParts = $env:GITHUB_REPOSITORY -split '/'
        $owner = $repoParts[0]
        $repo = $repoParts[1]
        # Construct the GitHub Pages URL
        $pagesUrl = "https://$owner.github.io/$repo"
        echo "::set-output name=pages_url::$pagesUrl"

    - name: Send email with test results for TPayWeb_V3
      if: always()
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: vasalanga@traxiontech.net
        subject: Playwright Test Result
        password: yszeszihrsqreloy
        to: salangavincent@gmail.com
        from: vasalanga@traxiontech.net
        body: |
            The Playwright tests for TPayWeb_V3 have completed. Please find the Allure report at the following link: ${{ steps.get-url.outputs.pages_url }}
            The report is hosted on GitHub Pages and will be available indefinitely.