name: Playwright Tests

on:
  schedule:
  - cron: '0 1 * * *'  
  workflow_dispatch:
     
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

        # Run Playwright tests Web
      - name: Run TraxionPay Merchant Playwright Tests
        if: always()
        run: |
          npx playwright test Main/Functional_Test/TPayWeb_V3 --project=Chromium 

        # Run Playwright tests Mobile
      #- name: Run TraxionPay Mobile Playwright Tests
      #  if: always()
      #  run: |
      #    npx playwright test Main/TPayMobile_V3 --project=Mobile

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report
          
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 1

  deploy-pages:
    if: always()
    needs: test-and-report
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-report
          keep_files: false
          publish_branch: gh-pages

  send-email:
    if: always()
    needs: deploy-pages
    runs-on: self-hosted
    steps:
      - name: Wait for Pages deployment
        run: |
          echo "Waiting for GitHub Pages to update (3 minutes)..."
          sleep 180
      - name: Send Report to email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: vasalanga@traxiontech.net
          subject: Playwright Test Result
          password: yszeszihrsqreloy
          to: 	salangavincent@gmail.com
          from: QA Team <vasalanga@traxiontech.net> 
          html_body: |
            <!DOCTYPE html>
              <html lang="en">
              <head>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                  <title>Test Results Notification</title>
                  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
              </head>
              <body style="font-family: 'Poppins', Arial, sans-serif; background-color: #f4f4f4; margin: 5px 0; padding: 25px; border-radius: 8px;">
                  <div style="max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);">
                      <!-- Header -->
                      <div style="text-align: center;">
                            <h1 style="color: #333333; margin: 5; padding-bottom: 10px;">🎭 Automation Test Results</h1>
                      </div>

                      <!-- Body Content -->
                      <div style="text-align: center; padding: 15px 30px;">
                          <p style="color: #555555; font-size: 16px; line-height: 1.6; margin: 0;">
                              The daily Automated tests for <strong>TraxionPay V3 - SIT</strong> have been completed. Click the button below to view the latest Test result:
                          </p>
                          
                          <!-- Call to Action Button -->
                          <a href="https://dread-vin.github.io/TraxionPay-V3/" 
                              style="display: inline-block; padding: 12px 24px; margin-top: 20px; font-size: 16px; font-weight: 600; color: #ffffff; 
                                    background-color: #41a4e2; border-radius: 6px; text-decoration: none; transition: 0.3s;">
                              View Allure Report
                          </a>
                      </div>

                      <!-- Disclaimer -->
                      <div style="text-align: center; padding-top: 20px; font-size: 14px; color: #777777;">
                          <p style="margin: 0;">This is an automated message. Please do not reply.</p>
                      </div>

                      <!-- Footer -->
                      <div style="margin-top: 20px; background-color: #f9f9f9; padding: 12px; border-radius: 0 0 8px 8px; text-align: center;">
                          <p style="font-size: 14px; color: #888888; margin: 0;"> TraxionTech | Vasalanga </p>
                      </div>

                    </div>
                </body>
              </html>
