name: Playwright Tests

on:
  #schedule:
  #- cron: '*/10 * * * *'  
  #workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run TPayWeb_V3 Playwright Tests
        if: always()
        run: | 
          npx playwright test Main/TPayWeb_V3 --project=chromium

      - name: Run TPayMobile_V3 Playwright Tests
        if: always()
        run: |
          npx playwright test Main/TPayMobile_V3 --project=mobile

      - name: Run TPayWeb_API_V3 Playwright Tests
        if: always()
        run: |
          npx playwright test Main/TPayWeb_API_V3 --project=chromium

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-report
          keep_files: false
          publish_branch: gh-pages

      - name: Send email with test results
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: vasalanga@traxiontech.net
          subject: Playwright Test Result
          password: yszeszihrsqreloy
          to: salangavincent@gmail.com
          from: vasalanga@traxiontech.net
          html_body: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Test Results Notification</title>
                <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
            </head>
            <body style="font-family: 'Poppins', Arial, sans-serif; background-color: #f4f4f4; margin: 5px 0; padding: 25px 0;  border-radius: 8px;">
                <div style="max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 5px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
                    <div style="text-align: center; padding-bottom: 0">
                        <h1 style="color: #333333; margin: 5; padding: 10px;">Test Results Notification</h1>
                    </div>
                    <div style="text-align: center; margin: 5; padding: 0 40px;">
                        <p style="color: #555555; font-size: 16px; line-height: 1.6;">
                            The Playwright tests for Traxion Pay Merchant V3 have completed. Please find the Allure report at the following link:
                        </p>
                        <a href="https://dread-vin.github.io/TraxionPay-V3/" 
                            style="display: inline-block; padding: 10px 20px; margin-top: 20px; font-size: 16px; color: #ffffff; background-color: #41C9E2; border-radius: 5px; text-decoration: none;">
                            View Allure Report
                        </a>
                    </div>
                    <div style="text-align: center; padding-top: 15px; font-size: 14px; color: #555555;">
                        <p>This is an automated message. Please do not reply.</p>
                    </div>
                    <hr style="border: none; border-top: 0.1px solid #555555; width: 80%; margin: 20px auto;">
                    <div style="text-align: center;  padding-bottom: 5px; font-size: 14px; color: #888888;">
                        <p>TraxionTech | Vasalanga.</p>
                    </div>
                </div>
            </body>
            </html>